export const ItemData = [
    {
        id : 1 ,
        title: "Silky Bưởi Ô Long Lài (M)",
        title1:"Pomêly - Ô Long Lài (MỚI)",
        image: "https://hcm.fstorage.vn/images/2024/05/01-20240507082336.png",
        prices:"55.000 ₫",

    },
    {
        id : 2 ,
        title: "Trà Sữa Phúc Long (M)",
        image: "https://hcm.fstorage.vn/images/2022/65000094-65000102-tra-sua-phuc-long-_3682b729-4ffc-4956-abb3-7026070663c2-og.png",
        prices:"45.000 ₫",

    },
    {
        id : 3 ,
        title: "Lục Trà Tân Cương Mận Đỏ (L)",
        title1:"Lục Bảo Tân Cương - Mới",
        image: "https://hcm.fstorage.vn/images/2024/07/man-do-20240724044039.png",
        prices:"65.000 ₫",

    },
    {
        id : 4 ,
        title: "Lục Trà Sữa Tân Cương Thạch Konjac (L)",
        title1:"Lục Bảo Tân Cương - Mới",
        image: "https://hcm.fstorage.vn/images/2024/07/luc-tra-sua-tan-cuong_png-20240711092721.png",
        prices:"60.000 ₫",

    },
    {
        id : 5 ,
        title: "Trà Bưởi Ô Long Lài (M)",
        title1:"Pomêly - Ô Long Lài (MỚI)",
        image: "https://hcm.fstorage.vn/images/2024/05/02-20240507082736.png",
        prices:"55.000 ₫",
    },
    
    
]
export const ItemData1 = [
    {
        id : 6 ,
        title: "Silky Bưởi Ô Long Lài (M)",
        title1:"Pomêly - Ô Long Lài (MỚI)",
        image: "https://hcm.fstorage.vn/images/2022/65000113-65000114-tra-vai-lai_319efb36-fcbf-45d9-8ad9-cb2ae2f7a90f-og.png",
        prices:"55.000 ₫",

    },
    {
        id : 7 ,
        title: "Trà Sữa Phúc Long (M)",
        image: "https://hcm.fstorage.vn/images/2022/65000094-65000102-tra-sua-phuc-long-_3682b729-4ffc-4956-abb3-7026070663c2-og.png",
        prices:"45.000 ₫",

    },
    {
        id : 8 ,
        title: "Trà Sữa Phúc Long (M)",
        image: "https://hcm.fstorage.vn/images/2022/65000094-65000102-tra-sua-phuc-long-_3682b729-4ffc-4956-abb3-7026070663c2-og.png",
        prices:"45.000 ₫",

    },
    {
        id : 9 ,
        title: "Trà Sữa Phúc Long (M)",
        image: "https://hcm.fstorage.vn/images/2022/65000094-65000102-tra-sua-phuc-long-_3682b729-4ffc-4956-abb3-7026070663c2-og.png",
        prices:"45.000 ₫",

    },
    {
        id : 10 ,
        title: "Trà Sữa Phúc Long (M)",
        image: "https://hcm.fstorage.vn/images/2022/65000094-65000102-tra-sua-phuc-long-_3682b729-4ffc-4956-abb3-7026070663c2-og.png",
        prices:"45.000 ₫",

    },
    {
        id : 11 ,
        title: "Trà Sữa Phúc Long (M)",
        image: "https://hcm.fstorage.vn/images/2022/65000094-65000102-tra-sua-phuc-long-_3682b729-4ffc-4956-abb3-7026070663c2-og.png",
        prices:"45.000 ₫",

    },
    {
        id : 12 ,
        title: "Trà Sữa Phúc Long (M)",
        image: "https://hcm.fstorage.vn/images/2022/65000094-65000102-tra-sua-phuc-long-_3682b729-4ffc-4956-abb3-7026070663c2-og.png",
        prices:"45.000 ₫",

    },
    {
        id : 13 ,
        title: "Trà Sữa Phúc Long (M)",
        image: "https://hcm.fstorage.vn/images/2022/65000094-65000102-tra-sua-phuc-long-_3682b729-4ffc-4956-abb3-7026070663c2-og.png",
        prices:"45.000 ₫",

    },
    {
        id : 14 ,
        title: "Trà Sữa Phúc Long (M)",
        image: "https://hcm.fstorage.vn/images/2022/65000094-65000102-tra-sua-phuc-long-_3682b729-4ffc-4956-abb3-7026070663c2-og.png",
        prices:"45.000 ₫",

    },
    {
        id : 15 ,
        title: "Trà Sữa Phúc Long (M)",
        image: "https://hcm.fstorage.vn/images/2022/65000094-65000102-tra-sua-phuc-long-_3682b729-4ffc-4956-abb3-7026070663c2-og.png",
        prices:"45.000 ₫",

    },
    {
        id : 16 ,
        title: "Trà Sữa Phúc Long (M)",
        image: "https://hcm.fstorage.vn/images/2022/65000094-65000102-tra-sua-phuc-long-_3682b729-4ffc-4956-abb3-7026070663c2-og.png",
        prices:"45.000 ₫",

    },
    {
        id : 17 ,
        title: "Trà Sữa Phúc Long (M)",
        image: "https://hcm.fstorage.vn/images/2022/65000094-65000102-tra-sua-phuc-long-_3682b729-4ffc-4956-abb3-7026070663c2-og.png",
        prices:"45.000 ₫",

    },
    {
        id : 18 ,
        title: "Trà Sữa Phúc Long (M)",
        image: "https://hcm.fstorage.vn/images/2022/65000094-65000102-tra-sua-phuc-long-_3682b729-4ffc-4956-abb3-7026070663c2-og.png",
        prices:"45.000 ₫",

    },
    {
        id : 19 ,
        title: "Trà Sữa Phúc Long (M)",
        image: "https://hcm.fstorage.vn/images/2022/65000094-65000102-tra-sua-phuc-long-_3682b729-4ffc-4956-abb3-7026070663c2-og.png",
        prices:"45.000 ₫",

    },
    {
        id : 20 ,
        title: "Trà Sữa Phúc Long (M)",
        image: "https://hcm.fstorage.vn/images/2022/65000094-65000102-tra-sua-phuc-long-_3682b729-4ffc-4956-abb3-7026070663c2-og.png",
        prices:"45.000 ₫",

    },
    {
        id : 21 ,
        title: "Trà Sữa Phúc Long (M)",
        image: "https://hcm.fstorage.vn/images/2022/65000094-65000102-tra-sua-phuc-long-_3682b729-4ffc-4956-abb3-7026070663c2-og.png",
        prices:"45.000 ₫",

    },
    {
        id : 22 ,
        title: "Trà Sữa Phúc Long (M)",
        image: "https://hcm.fstorage.vn/images/2022/65000094-65000102-tra-sua-phuc-long-_3682b729-4ffc-4956-abb3-7026070663c2-og.png",
        prices:"45.000 ₫",

    },
    {
        id : 23 ,
        title: "Trà Sữa Phúc Long (M)",
        image: "https://hcm.fstorage.vn/images/2022/65000094-65000102-tra-sua-phuc-long-_3682b729-4ffc-4956-abb3-7026070663c2-og.png",
        prices:"45.000 ₫",

    },
    {
        id : 24 ,
        title: "Trà Sữa Phúc Long (M)",
        image: "https://hcm.fstorage.vn/images/2022/65000094-65000102-tra-sua-phuc-long-_3682b729-4ffc-4956-abb3-7026070663c2-og.png",
        prices:"45.000 ₫",

    },
    {
        id : 25 ,
        title: "Trà Sữa Phúc Long (M)",
        image: "https://hcm.fstorage.vn/images/2022/65000094-65000102-tra-sua-phuc-long-_3682b729-4ffc-4956-abb3-7026070663c2-og.png",
        prices:"45.000 ₫",

    },
    {
        id : 26 ,
        title: "Trà Sữa Phúc Long (M)",
        image: "https://hcm.fstorage.vn/images/2022/65000094-65000102-tra-sua-phuc-long-_3682b729-4ffc-4956-abb3-7026070663c2-og.png",
        prices:"45.000 ₫",

    },
    {
        id : 27 ,
        title: "Trà Sữa Phúc Long (M)",
        image: "https://hcm.fstorage.vn/images/2022/65000094-65000102-tra-sua-phuc-long-_3682b729-4ffc-4956-abb3-7026070663c2-og.png",
        prices:"45.000 ₫",

    },
]
export const ItemData2 = [
    {
        id : 28 ,
        title: "Trà Sữa Ô Long Quế Hoa (M)",
        image: "https://hcm.fstorage.vn/images/2023/09/single1-copy-2-1--20230921061658.png",
        prices:"50.000 ₫",
    },
    {
        id : 29 ,
        title: "Trà Silky Ô Long Quế Hoa (M)",
        image: "https://hcm.fstorage.vn/images/2023/09/single4-copy-2-1--20230921062302.png",
        prices:"50.000 ₫",
    },
]
export const ItemData3 = [
    {
        id : 30 ,
        title: "Hồng Trà Đào (M)",
        image: "https://hcm.fstorage.vn/images/2022/65000085-65000100-tra-dao-phuc-long_b57f8c46-3096-42be-b8bc-84185ea3ec02-og.png",
        prices:"50.000 ₫",
    },
    {
        id : 31 ,
        title: "Trà Lucky Tea (M)",
        image: "https://hcm.fstorage.vn/images/2024/01/lucky-tea-20240104020604.png",
        prices:"50.000 ₫",
    },
    {
        id : 32 ,
        title: "Trà Nhãn Sen (M)",
        image: "https://hcm.fstorage.vn/images/2023/04/65000125-tra-nhan-sen-20230413023131.png",
        prices:"50.000 ₫",
    },
    {
        id : 33 ,
        title: "Trà Lài Đác Thơm (M)",
        image: "https://hcm.fstorage.vn/images/2022/65000133-65000134-tra-lai-dac-thom_72db1c57-d4b1-4889-95bf-840fea1341b6-og.png",
        prices:"50.000 ₫",
    },
    {
        id : 34 ,
        title: "Trà Vải Lài (M)",
        image: "https://hcm.fstorage.vn/images/2022/65000113-65000114-tra-vai-lai_319efb36-fcbf-45d9-8ad9-cb2ae2f7a90f-og.png",
        prices:"50.000 ₫",
    },
]
export const ItemData4 = [
    {
        id : 35 ,
        title: "Cappuccino Đá Xay",
        image: "https://hcm.fstorage.vn/images/2022/65000003-ca-phe-cappuccino-da-xay_47179b90-3960-4478-84c4-1f74b3fa1248-og.png",
        prices:"60.000 ₫",
    },
    {
        id : 36 ,
        title: "Sữa Chua Xoài Đác Thơm",
        image: "https://hcm.fstorage.vn/images/2022/65000073-sua-chua-xoai-dac-thom-phuc-long_26595644-4b5d-4d95-a3ff-d0ccf06d6f1f-og.png",
        prices:"70.000 ₫",
    },
    {
        id : 37 ,
        title: "Đá xay Matcha",
        image: "https://hcm.fstorage.vn/images/2023/12/matcha-da-xay-compress-20231208031242.png",
        prices:"70.000 ₫",
    },
    {
        id : 38 ,
        title: "Hồng Trà Đác Cam Đá Xay",
        image: "https://hcm.fstorage.vn/images/2022/65000135-hong-tra-dac-cam_7659ba61-7640-45fe-b899-3c882cf7b64f-og.png",
        prices:"70.000 ₫",
    },
]
export const ItemData5 = [
    {
        id : 39 ,
        title: "Cà Phê Đen Đá (M)",
        image: "https://hcm.fstorage.vn/images/2022/dmcap081-dmcap083-phin-den-da_d852660d-1e23-46bd-a1af-117247dc77f0-og.png",
        prices:"30.000 ₫",
    },
    {
        id : 40 ,
        title: "Cà Phê Sữa Đá (M)",
        image: "https://hcm.fstorage.vn/images/2022/dmcap082-dmcap084-phin-sua-da_3795a527-1b5b-4aaa-9d92-0d82385e4406-og.png",
        prices:"35.000 ₫",
    },
    {
        id : 41 ,
        title: "Cà phê Latte (M)",
        image: "https://hcm.fstorage.vn/images/2022/dmcap089-dmcap090-latte-latte_05488e79-cc32-4828-a5a3-3171f13ac845-og.png",
        prices:"45.000 ₫",
    },
    {
        id : 42 ,
        title: "Cà phê Cappuccino (M)",
        image: "https://hcm.fstorage.vn/images/2022/dmcap093-dmcap094-cappuccino-vietnamo_55905766-ff9f-435b-aa3b-e14018c188a3-og.png",
        prices:"45.000 ₫",
    },
]
export const ItemData6 = [
    {
        id : 43 ,
        title: "Trà Sữa Socola (M)",
        image: "https://hcm.fstorage.vn/images/2023/04/65000011-tra-sua-socola-20230407020111.png",
        prices:"45.000 ₫",
        title1: "Mới"
    },
    {
        id : 44 ,
        title: "Hồng Trà Đào Sữa Thạch Konjac (M)",
        image: "https://hcm.fstorage.vn/images/2022/65000086-65000103-tra-dao-sua_e1d1ff51-2c3f-4870-a3d5-9a1388c4d63f-og.png",
        prices:"50.000 ₫",
    },
    {
        id : 45 ,
        title: "Trà Sữa Matcha (M)",
        image: "https://hcm.fstorage.vn/images/2023/12/tra-sua-matcha-compress-20231208031011.png",
        prices:"45.000 ₫",
    },
    {
        id : 46 ,
        title: "Hồng Trà Sữa (M)",
        image: "https://hcm.fstorage.vn/images/2022/65000082-65000099-hong-tra-sua_30c9a4d2-957e-4152-b377-33b68f4da0c5-og.png",
        prices:"45.000 ₫",
    },
    {
        id : 47 ,
        title: "Trà Sữa Ô Long (M)",
        image: "https://hcm.fstorage.vn/images/2022/65000087-65000101-tra-o-long-sua_b2aa9ed3-4cc8-43e2-932b-802878bf314d-og.png",
        prices:"45.000 ₫",
    },
    {
        id : 48 ,
        title: "Trà Sữa Lài (M)",
        image: "https://hcm.fstorage.vn/images/2023/04/65000094-65000102-tra-sua-phuc-long--20230406103801.png",
        prices:"45.000 ₫",
        title1: "Mới",
    },
]
export const ItemData7 = [
    {
        id : 49 ,
       title: "Trà Sữa Phúc Long (M)",
        image: "https://hcm.fstorage.vn/images/2022/65000094-65000102-tra-sua-phuc-long-_3682b729-4ffc-4956-abb3-7026070663c2-og.png",
        prices:"45.000 ₫",
    },
    {
        id : 50 ,
       title: "Trà Phúc Long Kem Silky (M)",
        image: "https://hcm.fstorage.vn/images/2024/01/silky-1--20240104031840.png",
        prices:"45.000 ₫",
    },
]
export const ItemData8 = [
    {
        id : 51 ,
        title: "Cà phê Arabica-Culi 200g",
        image: "https://hcm.fstorage.vn/images/2022/60000452-ca-phe-arabica-culi-200g_6b73b763-e18e-4570-a8c3-04131993e66d-og.jpg",
        prices:"65.000 ₫",
        textdsc:"Thông tin sản phẩm",
        textdsc1:"Hướng dẫn sử dụng",
        textli:"Quy cách: 200 g",
        textli1:"Mô tả: Hương cà phê Arabica rất thơm, có vị chua, sau khi uống đọng lại cảm giác ngọt ở cổ họng. Arabica Cầu Đất có vị chua thanh xen lẫn với vị đắng nhẹ, nước pha màu nước nâu nhạt, trong trẻo của hổ phách. Mùi hương của Arabica rất thanh tao, quý phái, Arabica có mùi của si-rô, mùi của hoa trái, hòa quyện với mùi của mật ong, và cà mùi bánh mì nướng, mùi của cánh đồng rơm buổi trưa hè… Arabica chinh phục những con người sành điệu ẩm thực nhất trên thế giới.",
        textli2:"Bảo quản: Nơi khô thoáng",
        textli3:"Hạn sử dụng: Xem trên bao bì",
        textli4:"Cách pha cà phê:",
        textli5:"- Tráng phin và tách bằng nước nóng.",
        textli6:"- Cho 3 - 4 muỗng cà phê (khoảng 15 - 20g) vào phin. Lắc nhẹ phin cho mặt cà phê bằng phẳng. Đậy lưới chèn cà phê, nhấn nhẹ.",
        textli7:"- Đổ khoảng 25ml nước sôi vào phin cho cà phê ngấm đều.",
        textli8:"- Cho thêm khoảng 45ml nước sôi vào phin, đậy nắp phin. Khoảng 5 phút là có thể dùng được."
    },
    {
        id : 52 ,
        title: "Cà phê Arabica-Culi 500g",
        image: "https://hcm.fstorage.vn/images/2022/60000452-ca-phe-arabica-culi-200g_6b73b763-e18e-4570-a8c3-04131993e66d-og.jpg",
        prices:"165.000 ₫",
        textdsc:"Thông tin sản phẩm",
        textdsc1:"Hướng dẫn sử dụng",
        textli:"Quy cách: 500 g",
        textli1:"Mô tả: Hương cà phê Arabica rất thơm, có vị chua, sau khi uống đọng lại cảm giác ngọt ở cổ họng. Arabica Cầu Đất có vị chua thanh xen lẫn với vị đắng nhẹ, nước pha màu nước nâu nhạt, trong trẻo của hổ phách. Mùi hương của Arabica rất thanh tao, quý phái, Arabica có mùi của si-rô, mùi của hoa trái, hòa quyện với mùi của mật ong, và cà mùi bánh mì nướng, mùi của cánh đồng rơm buổi trưa hè… Arabica chinh phục những con người sành điệu ẩm thực nhất trên thế giới.",
        textli2:"Bảo quản: Nơi khô thoáng",
        textli3:"Hạn sử dụng: Xem trên bao bì",
        textli4:"Cách pha cà phê:",
        textli5:"- Tráng phin và tách bằng nước nóng.",
        textli6:"- Cho 3 - 4 muỗng cà phê (khoảng 15 - 20g) vào phin. Lắc nhẹ phin cho mặt cà phê bằng phẳng. Đậy lưới chèn cà phê, nhấn nhẹ.",
        textli7:"- Đổ khoảng 25ml nước sôi vào phin cho cà phê ngấm đều.",
        textli8:"- Cho thêm khoảng 45ml nước sôi vào phin, đậy nắp phin. Khoảng 5 phút là có thể dùng được."
    },
    {
        id : 53 ,
        title: "Cà phê rang nguyên hạt Culi 200g",
        image: "https://hcm.fstorage.vn/images/2022/60000487-ca-phe-culi-phuc-long-200g_f9d5b111-a643-4505-9d5f-8c28a49e86da-og.png",
        prices:"55.000 ₫",
        textdsc:"Thông tin sản phẩm",
        textdsc1:"Hướng dẫn sử dụng",
        textli:"Quy cách: 200 g",
        textli1:"Mô tả: Hạt cà phê Culi là những hạt cà phê no tròn. Đặc biệt là trong một trái chỉ có duy nhất một hạt. Vị đắng gắt, hương thơm say đắm, hàm lượng cafein cao, nuớc màu đen sánh đó là những gì mà Culi mang đến. Đó là quá trình kết hợp tinh túy của sự duy nhất.\n Đối với cà phê Culi Robusta, đây là loại cà phê có hương vị đậm đà hơn, đắng hơn, béo hơn, cafein nhiều hơn so với cà phê robusta thông thường, hương thơm sâu lắng, có vị chát, hậu vị đắng kéo dài. Phù hợp với người thích cafe đắng đậm, thích sự sâu lắng.",
        textli2:"Bảo quản: Nơi khô thoáng",
        textli3:"Hạn sử dụng: Xem trên bao bì",
        textli4:"Cách pha cà phê:",
        textli5:"- Tráng phin và tách bằng nước nóng.",
        textli6:"- Cho 3 - 4 muỗng cà phê (khoảng 15 - 20g) vào phin. Lắc nhẹ phin cho mặt cà phê bằng phẳng. Đậy lưới chèn cà phê, nhấn nhẹ.",
        textli7:"- Đổ khoảng 25ml nước sôi vào phin cho cà phê ngấm đều.",
        textli8:"- Cho thêm khoảng 45ml nước sôi vào phin, đậy nắp phin. Khoảng 5 phút là có thể dùng được."
    },
    {
        id : 54 ,
        title: "Cà phê rang nguyên hạt Culi 200g",
        image: "https://hcm.fstorage.vn/images/2022/60000487-ca-phe-culi-phuc-long-200g_f9d5b111-a643-4505-9d5f-8c28a49e86da-og.png",
        prices:"55.000 ₫",
        textdsc:"Thông tin sản phẩm",
        textdsc1:"Hướng dẫn sử dụng",
        textli:"Quy cách: 200 g",
        textli1:"Mô tả: Hạt cà phê Culi là những hạt cà phê no tròn. Đặc biệt là trong một trái chỉ có duy nhất một hạt. Vị đắng gắt, hương thơm say đắm, hàm lượng cafein cao, nuớc màu đen sánh đó là những gì mà Culi mang đến. Đó là quá trình kết hợp tinh túy của sự duy nhất.\n Đối với cà phê Culi Robusta, đây là loại cà phê có hương vị đậm đà hơn, đắng hơn, béo hơn, cafein nhiều hơn so với cà phê robusta thông thường, hương thơm sâu lắng, có vị chát, hậu vị đắng kéo dài. Phù hợp với người thích cafe đắng đậm, thích sự sâu lắng.",
        textli2:"Bảo quản: Nơi khô thoáng",
        textli3:"Hạn sử dụng: Xem trên bao bì",
        textli4:"Cách pha cà phê:",
        textli5:"- Tráng phin và tách bằng nước nóng.",
        textli6:"- Cho 3 - 4 muỗng cà phê (khoảng 15 - 20g) vào phin. Lắc nhẹ phin cho mặt cà phê bằng phẳng. Đậy lưới chèn cà phê, nhấn nhẹ.",
        textli7:"- Đổ khoảng 25ml nước sôi vào phin cho cà phê ngấm đều.",
        textli8:"- Cho thêm khoảng 45ml nước sôi vào phin, đậy nắp phin. Khoảng 5 phút là có thể dùng được."
    },
    {
        id : 55 ,
        title: "Cà phê rang nguyên hạt Culi 500g",
        image: "https://hcm.fstorage.vn/images/2022/60000487-ca-phe-culi-phuc-long-200g_f9d5b111-a643-4505-9d5f-8c28a49e86da-og.png",
        prices:"135.000 ₫",
        textdsc:"Thông tin sản phẩm",
        textdsc1:"Hướng dẫn sử dụng",
        textli:"Quy cách: 500 g",
        textli1:"Mô tả: Hạt cà phê Culi là những hạt cà phê no tròn. Đặc biệt là trong một trái chỉ có duy nhất một hạt. Vị đắng gắt, hương thơm say đắm, hàm lượng cafein cao, nuớc màu đen sánh đó là những gì mà Culi mang đến. Đó là quá trình kết hợp tinh túy của sự duy nhất.\n Đối với cà phê Culi Robusta, đây là loại cà phê có hương vị đậm đà hơn, đắng hơn, béo hơn, cafein nhiều hơn so với cà phê robusta thông thường, hương thơm sâu lắng, có vị chát, hậu vị đắng kéo dài. Phù hợp với người thích cafe đắng đậm, thích sự sâu lắng.",
        textli2:"Bảo quản: Nơi khô thoáng",
        textli3:"Hạn sử dụng: Xem trên bao bì",
        textli4:"Cách pha cà phê:",
        textli5:"- Tráng phin và tách bằng nước nóng.",
        textli6:"- Cho 3 - 4 muỗng cà phê (khoảng 15 - 20g) vào phin. Lắc nhẹ phin cho mặt cà phê bằng phẳng. Đậy lưới chèn cà phê, nhấn nhẹ.",
        textli7:"- Đổ khoảng 25ml nước sôi vào phin cho cà phê ngấm đều.",
        textli8:"- Cho thêm khoảng 45ml nước sôi vào phin, đậy nắp phin. Khoảng 5 phút là có thể dùng được."
    },
    {
        id : 56 ,
        title: "Cà phê rang nguyên hạt King 200g",
        image: "https://hcm.fstorage.vn/images/2022/60000487-ca-phe-culi-phuc-long-200g_f9d5b111-a643-4505-9d5f-8c28a49e86da-og.png",
        prices:"80.000 ₫",
        textdsc:"Thông tin sản phẩm",
        textdsc1:"Hướng dẫn sử dụng",
        textli:"Quy cách: 200 g",
        textli1:"Mô tả: Cà phê King là sự kết hợp hài hòa giữa 3 loại hạt Arabica, Robusta và Culi. Hương thơm nồng và vị cà phê mạnh mẽ, màu đen sánh đậm",
        textli2:"Bảo quản: Nơi khô thoáng",
        textli3:"Hạn sử dụng: Xem trên bao bì",
        textli4:"Cách pha cà phê:",
        textli5:"- Tráng phin và tách bằng nước nóng.",
        textli6:"- Cho 3 - 4 muỗng cà phê (khoảng 15 - 20g) vào phin. Lắc nhẹ phin cho mặt cà phê bằng phẳng. Đậy lưới chèn cà phê, nhấn nhẹ.",
        textli7:"- Đổ khoảng 25ml nước sôi vào phin cho cà phê ngấm đều.",
        textli8:"- Cho thêm khoảng 45ml nước sôi vào phin, đậy nắp phin. Khoảng 5 phút là có thể dùng được."
    },
    {
        id : 57 ,
        title: "Cà phê rang nguyên hạt Moka 500g",
        image: "https://hcm.fstorage.vn/images/2022/60000528-ca-phe-moka-khong-bo-phuc-long-500g_300caccc-ffbe-4e12-879c-22b7488fb636-og.png",
        prices:"215.000 ₫",
        textdsc:"Thông tin sản phẩm",
        textdsc1:"Hướng dẫn sử dụng",
        textli:"Quy cách: 500 g",
        textli1:"Mô tả: Cà phê Moka thuộc dòng sản phẩm của Arabica, hạt có hình dáng thon dài và đường rãnh lượn sóng ở giữa hạt. Cà phê Moka có hương thơm nhẹ nhàng quyến rũ rất đặc trưng, vị từ chua chuyển sang hậu đắng rất đặc biệt. Khi pha cà phê có màu nâu nhạt sánh. Cà phê Moka sẽ là lựa chọn tuyệt vời cho những ai yêu thích cà phê sữa.",
        textli2:"Bảo quản: Nơi khô thoáng",
        textli3:"Hạn sử dụng: Xem trên bao bì",
        textli4:"Cách pha cà phê:",
        textli5:"- Tráng phin và tách bằng nước nóng.",
        textli6:"- Cho 3 - 4 muỗng cà phê (khoảng 15 - 20g) vào phin. Lắc nhẹ phin cho mặt cà phê bằng phẳng. Đậy lưới chèn cà phê, nhấn nhẹ.",
        textli7:"- Đổ khoảng 25ml nước sôi vào phin cho cà phê ngấm đều.",
        textli8:"- Cho thêm khoảng 45ml nước sôi vào phin, đậy nắp phin. Khoảng 5 phút là có thể dùng được."
    },
]
export const ItemData9 = [
    {
        id : 58 ,
        title: "Trà lài ủ lạnh túi tgiác 2gx12gói C Brew",
        image: "https://hcm.fstorage.vn/images/2022/60000103-tra-lai-u-lanh-tui-tam-giac_67d9ae74-5d48-451f-8f14-bd013eb0830e-og.png",
        prices:"114.000 ₫",
        textdsc:"Thông tin sản phẩm",
        textdsc1:"Hướng dẫn sử dụng",
        textli:"Quy cách: 2g x 12 túi",
        textli1:"Mô tả: Trà Lài ủ lạnh được chế biến từ lá trà thượng hạng cùng hương hoa lài tự nhiên. Trải qua quy trình sản xuất khép kín, đảm bảo cho trà có thể hoà quyện cả hương lẫn vị. ",
        textli2:"Bảo quản: Nơi khô thoáng",
        textli3:"Hạn sử dụng: Xem trên bao bì",
        textli4:"Thực hiện pha trà ủ lạnh như sau:",
        textli5:"- Cho túi trà 2g vào bình hoặc chai chứa 350ml nước tinh khiết và đặt bình vào ngăn mát tủ lạnh khoảng 10-12 tiếng là có thể thưởng thức.",
        textli6:"- Ngoài ra, có thể biến tấu hương vị trà ủ lạnh phù hợp khẩu vị bằng cách thêm vào những nguyên liệu quen thuộc như mật ong, chanh, gừng hay quế.",
        textli7:"- Chai thủy tinh được khuyến khích sử dụng trong quá trình ủ lạnh để phản ánh trung thực vị trà, chất trà mềm mượt trọn vị, đồng thời thành phẩm không bị pha tạp mùi vị từ những chất liệu khác mang lại.",
    },
    {
        id : 59 ,
        title: "Trà Olong hộp oval 100g",
        image: "https://hcm.fstorage.vn/images/2022/60000171-tra-o-long-hop-oval-phuc-long_4e0436ec-4622-4acd-9834-0ac531c974dc-og.png",
        prices:"142.000 ₫",
        textdsc:"Thông tin sản phẩm",
        textdsc1:"Hướng dẫn sử dụng",
        textli:"Quy cách: 100 g",
        textli1:"Mô tả: Trà Ô long là dòng trà có hương vị đặc trưng được biết đến như một đại danh trà. Trà Ô long được thu hoạch theo nguyên lý “1 búp 3 lá” chế biến độc đáo với cách thức bán lên men tự nhiên, khi thấy màu lá chuyển sang ba phần đỏ bảy phần đen là thời điểm ủ tốt nhất để có được mùi vị thơm ngon nhất. Trà Ô long thành phẩm có dạng viên hình cầu, khi pha trà có sắc xanh tươi mát hòa quyện cùng hương hoa cỏ thoang thoảng khiến tâm hồn thêm thư thái. Dư vị hậu đắng của trà mang lại cho người dùng trải nghiệm khó quên khi thưởng thức.",
        textli2:"Bảo quản: Nơi khô thoáng",
        textli3:"Hạn sử dụng: Xem trên bao bì",
        textli4:"Cách pha trà:",
        textli5:"- Tráng ấm trà và tách trà bằng nước nóng",
        textli6:"- Dùng 100ml nước sôi rót vào ấm trà cùng với 5g trà.",
        textli7:"- Đợi khoảng 2 - 3 phút là có thể dùng được với hương vị tự nhiên của trà Phúc Long",
    },
    {
        id : 60 ,
        title: "Trà lài 15 200g",
        image: "https://hcm.fstorage.vn/images/2022/60000075-60000076-tra-lai-15_eabee765-a51b-4d38-9487-d784f56be6b3-og.jpg",
        prices:"105.000 ₫",
        textdsc:"Thông tin sản phẩm",
        textdsc1:"Hướng dẫn sử dụng",
        textli:"Quy cách: 200 g",
        textli1:"Mô tả: Trà lài là sự kết hợp hoàn hảo giữa lá trà xanh chất lượng cao và hoa lài. Trà có mùi thơm tự nhiên của hoa lài, màu vàng đẹp, vị ngọt của hoa lài và vị đắng nhẹ của trà tạo nên cảm giác khoan khoái và thư giãn cho người dùng.",
        textli2:"Bảo quản: Nơi khô thoáng",
        textli3:"Hạn sử dụng: Xem trên bao bì",
        textli4:"Cách pha trà:",
        textli5:"- Tráng ấm trà và tách trà bằng nước nóng",
        textli6:"- Dùng 100ml nước sôi rót vào ấm trà cùng với 5g trà.",
        textli7:"- Đợi khoảng 2 - 3 phút là có thể dùng được với hương vị tự nhiên của trà Phúc Long",
    },
    {
        id : 61 ,
        title: "Trà Olong 80 - 96g (12gx8 gói) Lon vuông",
        image: "https://hcm.fstorage.vn/images/2022/60000211-tra-o-long-thuong-hang_3b9c7bbe-5d23-43e9-a117-81577bc522a9-og.png",
        prices:"436.000 ₫",
        textdsc:"Thông tin sản phẩm",
        textdsc1:"Hướng dẫn sử dụng",
        textli:"Quy cách: 96 g (12 g x 8 gói)",
        textli1:"Mô tả: Trà Ô Long Thượng Hạng lon thiếc không chỉ lưu giữ được hương vị tươi ngon của lá trà mà còn gửi gắm những giá trị truyền thống trong văn hoá thưởng trà của người Việt. Sản phẩm được đóng gói và thiết kế đẹp mắt, lịch sự, nhã nhặn phù hợp dùng làm quà biếu tri ân. Trao gửi những lon trà thắm đượm hồn dân tộc là một nét văn hoá cần được giữ gìn và phát huy trong thời đại ngày nay.",
        textli2:"Bảo quản: Nơi khô thoáng",
        textli3:"Hạn sử dụng: Xem trên bao bì",
        textli4:"Cách pha trà:",
        textli5:"- Tráng ấm trà và tách trà bằng nước nóng",
        textli6:"- Cho khoảng 12g trà vào ấm, sau đó chế vào 250 – 300 ml nước sôi, đợi 10 giây rồi rót bỏ, gọi là rửa trà.",
        textli7:"- Đổ lượng nước sôi như trên vào ấm trà, hãm trà khoảng 2 phút là có thể thưởng thức.",
        textli8:"- Trà có thể pha đến 5 – 6 nước mà vẫn giữ được hương vị."
    },
    {
        id : 62 ,
        title: "Trà olong 80-150g",
        image: "https://hcm.fstorage.vn/images/2022/60000184-tra-o-long-80-150g_950a7bee-fbbe-491f-896a-3cca5c68747b-og.png",
        prices:"160.000 ₫",
        textdsc:"Thông tin sản phẩm",
        textdsc1:"Hướng dẫn sử dụng",
        textli:"Quy cách: 150 g",
        textli1:"Mô tả: Trà Ô long là dòng trà có hương vị đặc trưng được biết đến như một đại danh trà. Trà Ô long được thu hoạch theo nguyên lý “1 búp 3 lá” chế biến độc đáo với cách thức bán lên men tự nhiên, khi thấy màu lá chuyển sang ba phần đỏ bảy phần đen là thời điểm ủ tốt nhất để có được mùi vị thơm ngon nhất.",
        textli2:"Bảo quản: Nơi khô thoáng",
        textli3:"Hạn sử dụng: Xem trên bao bì",
        textli4:"Cách pha trà:",
        textli5:"- Tráng ấm trà và tách trà bằng nước nóng",
        textli6:"- Dùng 100ml nước sôi rót vào ấm trà cùng với 5g trà.",
        textli7:"- Đợi khoảng 2 - 3 phút là có thể dùng được với hương vị tự nhiên của trà Phúc Long",
    },
    {
        id : 63 ,
        title: "Trà lài hộp giấy 150g",
        image: "https://hcm.fstorage.vn/images/2022/60000072-tra-lai-hop-giay_d078fcf5-b941-4b6b-b9f7-e38736346ec5-og.png",
        prices:"75.000 ₫",
        textdsc:"Thông tin sản phẩm",
        textdsc1:"Hướng dẫn sử dụng",
        textli:"Quy cách: 150 g",
        textli1:"Mô tả: Trà lài là sự kết hợp hoàn hảo giữa lá trà xanh chất lượng cao và hoa lài. Trà được lên men và pha trộn với hoa lài, quá trình này được lặp lại nhiều lần giúp cho trà có mùi thơm tự nhiên của hoa lài, trà lài khi pha có màu vàng đẹp, vị ngọt của hoa lài và vị đắng nhẹ của trà tạo nên cảm giác khoan khoái và thư giãn cho người dùng.",
        textli2:"Bảo quản: Nơi khô thoáng",
        textli3:"Hạn sử dụng: Xem trên bao bì",
        textli4:"Cách pha trà:",
        textli5:"- Tráng ấm trà và tách trà bằng nước nóng",
        textli6:"- Dùng 100ml nước sôi rót vào ấm trà cùng với 5g trà.",
        textli7:"- Đợi khoảng 2 - 3 phút là có thể dùng được với hương vị tự nhiên của trà Phúc Long",
    },
    {
        id : 64 ,
        title: "Trà Nõn tôm ủ lạnh túi tgiác 2gx12gói CB",
        image: "https://hcm.fstorage.vn/images/2022/60000162-tra-non-tom-u-lanh-tui-tam-giac_53c6ea81-dc90-4e8d-b71b-a7c6403fde78-og.png",
        prices:"75.000 ₫",
        textdsc:"Thông tin sản phẩm",
        textdsc1:"Hướng dẫn sử dụng",
        textli:"Quy cách: 2g x 12 túi",
        textli1:"Mô tả: Trà Nõn Tôm là loại trà thượng hạng được vun trồng tại vùng đất Tân Cương - Thái Nguyên. Xuyên suốt quá trình chế biến được thực hiện tỉ mỉ và chuẩn xác, từ thu hái và sao chế hoàn toàn bằng phương pháp thủ công nhằm gìn giữ đặc tính thượng hạng của lá trà. Khi pha tạo nên chất trà vàng xanh thắm đượm xen lẫn vị chát dịu, đậm đà, hoà quyện cùng hương thơm cốm mới thuần khiết.",
        textli2:"Bảo quản: Nơi khô thoáng",
        textli3:"Hạn sử dụng: Xem trên bao bì",
        textli4:"Thực hiện pha trà ủ lạnh như sau:",
        textli5:"- Cho túi trà 2g vào bình hoặc chai chứa 350ml nước tinh khiết và đặt bình vào ngăn mát tủ lạnh khoảng 10-12 tiếng là có thể thưởng thức.",
        textli6:"- Ngoài ra, có thể biến tấu hương vị trà ủ lạnh phù hợp khẩu vị bằng cách thêm vào những nguyên liệu quen thuộc như mật ong, chanh, gừng hay quế.",
        textli7:"- Chai thủy tinh được khuyến khích sử dụng trong quá trình ủ lạnh để phản ánh trung thực vị trà, chất trà mềm mượt trọn vị, đồng thời thành phẩm không bị pha tạp mùi vị từ những chất liệu khác mang lại.",
    },
    {
        id : 65 ,
        title: "Trà đen Phúc Long 500g",
        image: "https://hcm.fstorage.vn/images/2022/60000021-tra-den-500g-phuc-long_52e73e0a-e09a-4e2c-8406-fc1dcb4da3e3-og.png",
        prices:"135.000 ₫",
        textdsc:"Thông tin sản phẩm",
        textdsc1:"Hướng dẫn sử dụng",
        textli:"Quy cách: 500 g",
        textli1:"Mô tả: Trà đen là trà xanh khi thu hoạch và được ủ lên men sau khi phơi khô. Phản ứng lên men giúp trà đen có mùi thơm đặc biệt và lá trà có màu sậm, từ đỏ hung đến đen tuyền. Trà đen với hậu vị chát đậm, khi uống chất trà thấm vào cơ thể nhẹ nhàng đánh thức các giác quan, tạo tâm trạng sảng khoái.",
        textli2:"Bảo quản: Nơi khô thoáng",
        textli3:"Hạn sử dụng: Xem trên bao bì",
        textli4:"Cách pha trà:",
        textli5:"- Tráng ấm trà và tách trà bằng nước nóng",
        textli6:"- Dùng 100ml nước sôi rót vào ấm trà cùng với 5g trà.",
        textli7:"- Đợi khoảng 2 - 3 phút là có thể dùng được với hương vị tự nhiên của trà Phúc Long",
    },
    {
        id : 66 ,
        title: "Trà olong 80 - 100g",
        image: "https://hcm.fstorage.vn/images/2022/60000177-tra-oolong-80-100g_b9c023fd-1f01-407d-b4f7-203d0bf066d7-og.png",
        prices:"130.000 ₫",
        textdsc:"Thông tin sản phẩm",
        textdsc1:"Hướng dẫn sử dụng",
        textli:"Quy cách: 100 g",
        textli1:"Mô tả: Trà Ô long là dòng trà có hương vị đặc trưng được biết đến như một đại danh trà. Trà Ô long được thu hoạch theo nguyên lý “1 búp 3 lá” chế biến độc đáo với cách thức bán lên men tự nhiên, khi thấy màu lá chuyển sang ba phần đỏ bảy phần đen là thời điểm ủ tốt nhất để có được mùi vị thơm ngon nhất.",
        textli2:"Bảo quản: Nơi khô thoáng",
        textli3:"Hạn sử dụng: Xem trên bao bì",
        textli4:"Cách pha trà:",
        textli5:"- Tráng ấm trà và tách trà bằng nước nóng",
        textli6:"- Dùng 100ml nước sôi rót vào ấm trà cùng với 5g trà.",
        textli7:"- Đợi khoảng 2 - 3 phút là có thể dùng được với hương vị tự nhiên của trà Phúc Long",
    },
    {
        id : 67 ,
        title: "Trà lài 15 500g",
        image: "https://hcm.fstorage.vn/images/2022/60000075-60000076-tra-lai-15_e8e5c826-4b67-4a9f-b82d-003170f3bf3d-og.jpg",
        prices:"250.000 ₫",
        textdsc:"Thông tin sản phẩm",
        textdsc1:"Hướng dẫn sử dụng",
        textli:"Quy cách: 500 g",
        textli1:"Mô tả: Trà lài là sự kết hợp hoàn hảo giữa lá trà xanh chất lượng cao và hoa lài. Trà có mùi thơm tự nhiên của hoa lài, màu vàng đẹp, vị ngọt của hoa lài và vị đắng nhẹ của trà tạo nên cảm giác khoan khoái và thư giãn cho người dùng.",
        textli2:"Bảo quản: Nơi khô thoáng",
        textli3:"Hạn sử dụng: Xem trên bao bì",
        textli4:"Cách pha trà:",
        textli5:"- Tráng ấm trà và tách trà bằng nước nóng",
        textli6:"- Dùng 100ml nước sôi rót vào ấm trà cùng với 5g trà.",
        textli7:"- Đợi khoảng 2 - 3 phút là có thể dùng được với hương vị tự nhiên của trà Phúc Long",
    },
    {
        id : 68 ,
        title: "Trà lài túi tam giác 3g x 10 gói - 1 hộp",
        image: "https://hcm.fstorage.vn/images/2022/60000093-tra-lai-tui-tam-giac-phuc-long_6365beb0-02a0-451f-bd04-594942b4483c-og.png",
        prices:"250.000 ₫",
        textdsc:"Thông tin sản phẩm",
        textdsc1:"Hướng dẫn sử dụng",
        textli:"Quy cách: 3g x 10 gói",
        textli1:"Mô tả: Trà lài là sự kết hợp hoàn hảo giữa lá trà xanh chất lượng cao và hoa lài. Trà có mùi thơm tự nhiên của hoa lài, màu vàng đẹp, vị ngọt của hoa lài và vị đắng nhẹ của trà tạo nên cảm giác khoan khoái và thư giãn cho người dùng.",
        textli2:"Bảo quản: Nơi khô thoáng",
        textli3:"Hạn sử dụng: Xem trên bao bì",
        textli4:"Cách pha trà: Cho gói trà vào tách, đổ nước sôi vào. Ngâm khoảng 2 - 3 phút, nhúng gói trà 5 lần rồi lấy ra. Giờ bạn có thể thưởng thức",
    },
    {
        id : 69 ,
        title: "Trà xanh Thái Nguyên 200g",
        image: "https://hcm.fstorage.vn/images/2022/60000370-60000369-tra-xanh-thai-nguyen_1ef7e968-c0ab-4328-878a-576d401c1d2e-og.png",
        prices:"55.000 ₫",
        textdsc:"Thông tin sản phẩm",
        textdsc1:"Hướng dẫn sử dụng",
        textli:"Quy cách: 200 g",
        textli1:"Mô tả: Trà lài là sự kết hợp hoàn hảo giữa lá trà xanh chất lượng cao và hoa lài. Trà có mùi thơm tự nhiên của hoa lài, màu vàng đẹp, vị ngọt của hoa lài và vị đắng nhẹ của trà tạo nên cảm giác khoan khoái và thư giãn cho người dùng.",
        textli2:"Bảo quản: Nơi khô thoáng",
        textli3:"Hạn sử dụng: Xem trên bao bì",
        textli4:"Cách pha trà:",
        textli5:"- Tráng ấm trà và tách trà bằng nước nóng",
        textli6:"- Dùng 100ml nước sôi rót vào ấm trà cùng với 5g trà.",
        textli7:"- Đợi khoảng 2 - 3 phút là có thể dùng được với hương vị tự nhiên của trà Phúc Long",
    },
    {
        id : 70 ,
        title: "Trà xanh Thái Nguyên 500g",
        image: "https://hcm.fstorage.vn/images/2022/60000370-60000369-tra-xanh-thai-nguyen_44dd052b-7ea6-497a-8584-0d67883f9e85-og.png",
        prices:"135.000 ₫",
        textdsc:"Thông tin sản phẩm",
        textdsc1:"Hướng dẫn sử dụng",
        textli:"Quy cách: 500 g",
        textli1:"Mô tả: Trà lài là sự kết hợp hoàn hảo giữa lá trà xanh chất lượng cao và hoa lài. Trà có mùi thơm tự nhiên của hoa lài, màu vàng đẹp, vị ngọt của hoa lài và vị đắng nhẹ của trà tạo nên cảm giác khoan khoái và thư giãn cho người dùng.",
        textli2:"Bảo quản: Nơi khô thoáng",
        textli3:"Hạn sử dụng: Xem trên bao bì",
        textli4:"Cách pha trà:",
        textli5:"- Tráng ấm trà và tách trà bằng nước nóng",
        textli6:"- Dùng 100ml nước sôi rót vào ấm trà cùng với 5g trà.",
        textli7:"- Đợi khoảng 2 - 3 phút là có thể dùng được với hương vị tự nhiên của trà Phúc Long",
    },
]
export const ItemData10 = [
    {
        id : 71 ,
        title: "Trà Olong 80 - 80g (Lon thiết vuông)",
        image: "https://hcm.fstorage.vn/images/2022/60000210-tra-o-long-thuong-hang_ebbc10d6-e2f9-45bb-8662-8dcc9f3d161d-og.png",
        prices:"380.000 ₫",
        textdsc:"Thông tin sản phẩm",
        textdsc1:"Hướng dẫn sử dụng",
        textli:"Quy cách: 80 g",
        textli1:"Mô tả: Trà Ô Long Thượng Hạng lon thiếc không chỉ lưu giữ được hương vị tươi ngon của lá trà mà còn gửi gắm những giá trị truyền thống trong văn hoá thưởng trà của người Việt. Sản phẩm được đóng gói và thiết kế đẹp mắt, lịch sự, nhã nhặn phù hợp dùng làm quà biếu tri ân. Trao gửi những lon trà thắm đượm hồn dân tộc là một nét văn hoá cần được giữ gìn và phát huy trong thời đại ngày nay.",
        textli2:"Bảo quản: Nơi khô thoáng",
        textli3:"Hạn sử dụng: Xem trên bao bì",
        textli4:"Cách pha trà:",
        textli5:"- Tráng ấm trà và tách trà bằng nước nóng",
        textli6:"- Cho khoảng 12g trà vào ấm, sau đó chế vào 250 – 300 ml nước sôi, đợi 10 giây rồi rót bỏ, gọi là rửa trà.",
        textli7:"- Đổ lượng nước sôi như trên vào ấm trà, hãm trà khoảng 2 phút là có thể thưởng thức.",
        textli8:"- Trà có thể pha đến 5 – 6 nước mà vẫn giữ được hương vị."
    },
    {
        id : 72 ,
        title: "Trà Olong 80 - 96g (12gx8 gói) Lon vuông",
        image: "https://hcm.fstorage.vn/images/2022/60000211-tra-o-long-thuong-hang_3b9c7bbe-5d23-43e9-a117-81577bc522a9-og.png",
        prices:"436.000 ₫",
        textdsc:"Thông tin sản phẩm",
        textdsc1:"Hướng dẫn sử dụng",
        textli:"Quy cách: 96 g (12 g x 8 gói)",
        textli1:"Mô tả: Trà Ô Long Thượng Hạng lon thiếc không chỉ lưu giữ được hương vị tươi ngon của lá trà mà còn gửi gắm những giá trị truyền thống trong văn hoá thưởng trà của người Việt. Sản phẩm được đóng gói và thiết kế đẹp mắt, lịch sự, nhã nhặn phù hợp dùng làm quà biếu tri ân. Trao gửi những lon trà thắm đượm hồn dân tộc là một nét văn hoá cần được giữ gìn và phát huy trong thời đại ngày nay.",
        textli2:"Bảo quản: Nơi khô thoáng",
        textli3:"Hạn sử dụng: Xem trên bao bì",
        textli4:"Cách pha trà:",
        textli5:"- Tráng ấm trà và tách trà bằng nước nóng",
        textli6:"- Cho khoảng 12g trà vào ấm, sau đó chế vào 250 – 300 ml nước sôi, đợi 10 giây rồi rót bỏ, gọi là rửa trà.",
        textli7:"- Đổ lượng nước sôi như trên vào ấm trà, hãm trà khoảng 2 phút là có thể thưởng thức.",
        textli8:"- Trà có thể pha đến 5 – 6 nước mà vẫn giữ được hương vị."
    },
]
export const ItemData11 = [
    {
        id : 59 ,
        title: "Trà Olong hộp oval 100g",
        image: "https://hcm.fstorage.vn/images/2022/60000171-tra-o-long-hop-oval-phuc-long_4e0436ec-4622-4acd-9834-0ac531c974dc-og.png",
        prices:"142.000 ₫",
        textdsc:"Thông tin sản phẩm",
        textdsc1:"Hướng dẫn sử dụng",
        textli:"Quy cách: 100 g",
        textli1:"Mô tả: Trà Ô long là dòng trà có hương vị đặc trưng được biết đến như một đại danh trà. Trà Ô long được thu hoạch theo nguyên lý “1 búp 3 lá” chế biến độc đáo với cách thức bán lên men tự nhiên, khi thấy màu lá chuyển sang ba phần đỏ bảy phần đen là thời điểm ủ tốt nhất để có được mùi vị thơm ngon nhất. Trà Ô long thành phẩm có dạng viên hình cầu, khi pha trà có sắc xanh tươi mát hòa quyện cùng hương hoa cỏ thoang thoảng khiến tâm hồn thêm thư thái. Dư vị hậu đắng của trà mang lại cho người dùng trải nghiệm khó quên khi thưởng thức.",
        textli2:"Bảo quản: Nơi khô thoáng",
        textli3:"Hạn sử dụng: Xem trên bao bì",
        textli4:"Cách pha trà:",
        textli5:"- Tráng ấm trà và tách trà bằng nước nóng",
        textli6:"- Dùng 100ml nước sôi rót vào ấm trà cùng với 5g trà.",
        textli7:"- Đợi khoảng 2 - 3 phút là có thể dùng được với hương vị tự nhiên của trà Phúc Long",
    },
]
export const ItemData12 = [
    {
        id : 73 ,
        title: "Bánh Butter chocolate croissant 45gr",
        image: "https://hcm.fstorage.vn/images/2022/60000639-butter-chocolate-croissant-45g_08fa60a8-dcbc-4e71-aabc-95c0370b9352-og.png",
        prices:"22.000 ₫",
    },
]
export const ItemData13 = [
    {
        id : 74 ,
        title: "Gà Quay Jambon 1TR 150G",
        image: "https://hcm.fstorage.vn/images/2024/07/ga-quay-jambon-copy-20240724110248.png",
        title1:"PHÚC LONG NIÊN - THƯỞNG MINH NGUYỆT",
        prices:"139.000 ₫",
    },
    {
        id : 75 ,
        title: "Thập Cẩm Jambon 1TR 150G",
        image: "https://hcm.fstorage.vn/images/2024/07/thap-cam-jambon-copy-20240725030923.png",
        title1:"PHÚC LONG NIÊN - THƯỞNG MINH NGUYỆT",
        prices:"139.000 ₫",
    },
    {
        id : 76 ,
        title: "Cua Bát Bửu 1TR 150G",
        image: "https://hcm.fstorage.vn/images/2024/07/cua-bat-buu-copy-20240724110219.png",
        title1:"PHÚC LONG NIÊN - THƯỞNG MINH NGUYỆT",
        prices:"169.000 ₫",
    },
    {
        id : 77 ,
        title: "Lava Choco Tan Chảy 150G",
        image: "https://hcm.fstorage.vn/images/2024/07/lava-choco-copy-20240724110626.png",
        title1:"PHÚC LONG NIÊN - THƯỞNG MINH NGUYỆT",
        prices:"129.000 ₫",
    },
    {
        id : 78 ,
        title: "Khoai Môn 1TR 150G",
        image: "https://hcm.fstorage.vn/images/2024/07/khoai-mon-copy-20240724110420.png",
        title1:"PHÚC LONG NIÊN - THƯỞNG MINH NGUYỆT",
        prices:"129.000 ₫",
    },
    {
        id : 79 ,
        title: "Sữa Dừa 1TR 150G",
        image: "https://hcm.fstorage.vn/images/2024/07/sua-dua-copy-20240724110454.png",
        title1:"PHÚC LONG NIÊN - THƯỞNG MINH NGUYỆT",
        prices:"129.000 ₫",
    },
    {
        id : 80 ,
        title: "Đậu Xanh Hạnh Nhân 1TR 150G",
        image: "https://hcm.fstorage.vn/images/2024/07/dau-xanh-hanh-nhan-copy-20240724110532.png",
        title1:"PHÚC LONG NIÊN - THƯỞNG MINH NGUYỆT",
        prices:"129.000 ₫",
    },
    {
        id : 81 ,
        title: "Tuyết Trà Xanh 150G",
        image: "https://hcm.fstorage.vn/images/2024/07/tuyet-tra-xanh-copy-20240724110703.png",
        title1:"PHÚC LONG NIÊN - THƯỞNG MINH NGUYỆT",
        prices:"129.000 ₫",
    },
]